import { addDays, subDays, formatISO } from 'date-fns';
import { Client, SalesTarget, User, Match, MatchStatus } from './types';

const now = new Date();

export const mockUsers: User[] = [
  { id: 'admin-sarah', name: 'Sarah (Admin)', role: 'crm_admin', email: 'sarah@datingcrm.com' },
  { id: 'admin-youssef', name: 'Youssef (Manager)', role: 'manager', email: 'youssef@datingcrm.com' },
  { id: 'rep-user', name: 'Matchmaker Rep', role: 'rep', email: 'matchmaker@datingcrm.com' },
];

export const mockPTPackages: any[] = [];

export const mockSalesTarget: SalesTarget = {
  targetAmount: 50000,
  currentAmount: 0,
  privateTarget: 0,
  groupTarget: 0,
  privatePackagesSold: 0,
  groupPackagesSold: 0,
};

export const mockClients: Client[] = [
  {
    id: 'g101',
    name: 'Ahmed Hassan',
    fullName: 'Ahmed Hassan El-Din',
    phone: '+20 100 123 4567',
    phoneNumber: '+20 100 123 4567',
    email: 'ahmed.hassan@example.com',
    status: 'Approved',
    gender: 'Male',
    code: 'G101',
    age: 28,
    finalAge: 28,
    locationOfResidence: 'Heliopolis, Cairo',
    height: '1.82',
    religion: 'Muslim',
    areYouGucian: 'Yes',
    gucId: '28-4930',
    universityFieldOfStudy: 'Engineering / Computer Science',
    currentJob: 'Product Manager at Valeo',
    maritalStatus: 'Single',
    haveChildren: 'No',
    smokeOrDrink: 'Non-smoker',
    currentFinancialStatus: 'Stable / High Income',
    religiousDenomination: 'Sunni',
    prayRegularly: 'Yes, regularly',
    religiousCommitmentLevel: 'Moderate',
    facebookLink: 'https://facebook.com/ahmed.hassan.pm',
    selfIntroduction: 'I am a passionate software engineer and product manager. Alumni of GUC. Enjoy working out, reading about tech startups, and hiking on weekends. Looking to build a stable, loving, and supportive relationship based on mutual respect and shared ambitions.',
    partnerPreferences: 'Looking for a kind, family-oriented, and educated woman. Preferably a GUC graduate or similar background. Someone who is understanding, career-oriented but appreciates family-first values.',
    assignedTo: 'admin-sarah',
    createdAt: formatISO(subDays(now, 10)),
    comments: [
      {
        id: 'c1',
        text: 'Initial consultation complete. Highly articulate and mature candidate. Verified GUC ID successfully.',
        date: formatISO(subDays(now, 10)),
        author: 'Sarah'
      }
    ],
    interactions: [
      {
        id: 'int1',
        date: formatISO(subDays(now, 10)),
        type: 'Visit',
        outcome: 'Scheduled Consultation',
        notes: 'In-office interview finished. All criteria verified.',
        author: 'Sarah'
      }
    ]
  },
  {
    id: 'g102',
    name: 'Omar Farouk',
    fullName: 'Omar Farouk Abdelrahman',
    phone: '+20 122 345 6789',
    phoneNumber: '+20 122 345 6789',
    email: 'omar.farouk@example.com',
    status: 'Approved',
    gender: 'Male',
    code: 'G102',
    age: 31,
    finalAge: 31,
    locationOfResidence: 'Maadi, Cairo',
    height: '1.78',
    religion: 'Muslim',
    areYouGucian: 'No',
    universityFieldOfStudy: 'Business Administration',
    currentJob: 'Co-founder & CEO of Fintech Startup',
    maritalStatus: 'Single',
    haveChildren: 'No',
    smokeOrDrink: 'Social smoker',
    currentFinancialStatus: 'Excellent / Entrepreneur',
    religiousDenomination: 'Sunni',
    prayRegularly: 'Yes',
    religiousCommitmentLevel: 'Moderate',
    facebookLink: 'https://facebook.com/omar.farouk.finance',
    selfIntroduction: 'I am a highly driven entrepreneur in the fintech sector. Love traveling, diving in Sharm, and playing football. Strongly believe in continuous self-improvement and looking for a life companion to share the journey.',
    partnerPreferences: 'An independent, smart, and career-driven woman who loves life and values personal space. Location of residence: Cairo.',
    assignedTo: 'admin-sarah',
    createdAt: formatISO(subDays(now, 8)),
    comments: [
      {
        id: 'c2',
        text: 'Polite and financially successful candidate. Prefers independent, smart partners.',
        date: formatISO(subDays(now, 8)),
        author: 'Sarah'
      }
    ],
    interactions: []
  },
  {
    id: 'g103',
    name: 'Karim Yassin',
    fullName: 'Karim Yassin Soliman',
    phone: '+20 101 222 3333',
    phoneNumber: '+20 101 222 3333',
    email: 'karim.yassin@example.com',
    status: 'Pending Review',
    gender: 'Male',
    code: 'G103',
    age: 26,
    finalAge: 26,
    locationOfResidence: 'Tagamoa, New Cairo',
    height: '1.85',
    religion: 'Muslim',
    areYouGucian: 'Yes',
    gucId: '26-1029',
    universityFieldOfStudy: 'Applied Sciences & Arts',
    currentJob: 'Creative Director at Cairo Ad Agency',
    maritalStatus: 'Single',
    haveChildren: 'No',
    smokeOrDrink: 'Non-smoker',
    currentFinancialStatus: 'Stable',
    religiousDenomination: 'Sunni',
    prayRegularly: 'Yes, trying',
    religiousCommitmentLevel: 'Moderate',
    facebookLink: 'https://facebook.com/karim.yassin.arts',
    selfIntroduction: 'I am an artist, designer, and filmmaker. Love visual arts, playing electric guitar, and cinema. Looking for a soulmate who appreciates aesthetics, arts, and deep, long conversations.',
    partnerPreferences: 'Artistic, highly educated, preferably working in a creative or academic field. Hijab preference: Optional / Open.',
    assignedTo: 'rep-user',
    createdAt: formatISO(subDays(now, 2)),
    comments: [
      {
        id: 'c3',
        text: 'Applied online. Undergoing phone screening. GUC student id verified.',
        date: formatISO(subDays(now, 2)),
        author: 'Matchmaker Staff'
      }
    ],
    interactions: []
  },
  {
    id: 'l101',
    name: 'Sara Mahmoud',
    fullName: 'Sara Mahmoud El-Shimi',
    phone: '+20 111 987 6543',
    phoneNumber: '+20 111 987 6543',
    email: 'sara.shimi@example.com',
    status: 'Approved',
    gender: 'Female',
    code: 'L101',
    age: 25,
    finalAge: 25,
    locationOfResidence: 'Zamalek, Cairo',
    height: '1.65',
    religion: 'Muslim',
    areYouGucian: 'Yes',
    gucId: '25-8302',
    universityFieldOfStudy: 'Architecture',
    currentJob: 'Senior Architect at Dar Al-Handasah',
    maritalStatus: 'Single',
    haveChildren: 'No',
    smokeOrDrink: 'Non-smoker',
    currentFinancialStatus: 'Stable',
    religiousDenomination: 'Sunni',
    prayRegularly: 'Yes, regularly',
    religiousCommitmentLevel: 'Moderate',
    facebookLink: 'https://facebook.com/sara.mahmoud.arch',
    selfIntroduction: 'I am an architect and painter. Passionate about historical restoration, tennis, and classical piano. Family is my absolute priority. I appreciate fine details and respect ambitious, caring individuals.',
    partnerPreferences: 'Ambitious, respectful, family-oriented, and highly supportive of my career. Must have similar social values and live in Cairo.',
    assignedTo: 'admin-sarah',
    createdAt: formatISO(subDays(now, 12)),
    comments: [
      {
        id: 'c4',
        text: 'Charming and exceptionally accomplished candidate. Highly recommended.',
        date: formatISO(subDays(now, 12)),
        author: 'Sarah'
      }
    ],
    interactions: []
  },
  {
    id: 'l102',
    name: 'Salma Dawood',
    fullName: 'Salma Dawood Fahmy',
    phone: '+20 106 666 8500',
    phoneNumber: '+20 106 666 8500',
    email: 'salma.dawood@example.com',
    status: 'Approved',
    gender: 'Female',
    code: 'L102',
    age: 29,
    finalAge: 29,
    locationOfResidence: 'Dokki, Giza',
    height: '1.68',
    religion: 'Muslim',
    areYouGucian: 'Yes',
    gucId: '29-0129',
    universityFieldOfStudy: 'Pharmacy',
    currentJob: 'Clinical Pharmacist at 57357 Hospital',
    maritalStatus: 'Single',
    haveChildren: 'No',
    smokeOrDrink: 'Non-smoker',
    currentFinancialStatus: 'Stable',
    religiousDenomination: 'Sunni',
    prayRegularly: 'Yes',
    religiousCommitmentLevel: 'High',
    facebookLink: 'https://facebook.com/salma.dawood.ph',
    selfIntroduction: 'A quiet, home-loving, and compassionate pharmacist. I spend my spare time reading, doing community service, and practicing yoga. Religion and moral character are very important to me.',
    partnerPreferences: 'A gentleman of solid moral character, honest, kind, and family-oriented. Must value stable and healthy communication.',
    assignedTo: 'rep-user',
    createdAt: formatISO(subDays(now, 5)),
    comments: [
      {
        id: 'c5',
        text: 'Kind-hearted pharmacist. Moral character is her top requirement.',
        date: formatISO(subDays(now, 5)),
        author: 'Matchmaker Staff'
      }
    ],
    interactions: []
  },
  {
    id: 'l103',
    name: 'Yasmine Sabry',
    fullName: 'Yasmine Sabry Mansour',
    phone: '+20 109 888 7777',
    phoneNumber: '+20 109 888 7777',
    email: 'yasmine.mansour@example.com',
    status: 'Hold',
    gender: 'Female',
    code: 'L103',
    age: 27,
    finalAge: 27,
    locationOfResidence: 'Tagamoa, New Cairo',
    height: '1.62',
    religion: 'Muslim',
    areYouGucian: 'No',
    universityFieldOfStudy: 'Languages & Translation',
    currentJob: 'German Customer Relations Team Lead',
    maritalStatus: 'Single',
    haveChildren: 'No',
    smokeOrDrink: 'Non-smoker',
    currentFinancialStatus: 'Stable',
    religiousDenomination: 'Sunni',
    prayRegularly: 'Yes',
    religiousCommitmentLevel: 'Moderate',
    facebookLink: 'https://facebook.com/yasmine.mansour.german',
    selfIntroduction: 'I am a cheerful and outgoing German customer team leader. Love outdoor adventures, exploring new coffee spots, and travel writing. Looking to settle down with someone who is positive and adventurous.',
    partnerPreferences: 'A positive, communicative, and respectful gentleman. Adventurous spirit and location of residence in Cairo are highly preferred.',
    assignedTo: 'admin-youssef',
    createdAt: formatISO(subDays(now, 15)),
    comments: [
      {
        id: 'c6',
        text: 'Requested to be put on Hold temporarily due to a heavy business travel schedule.',
        date: formatISO(subDays(now, 1)),
        author: 'Youssef'
      }
    ],
    interactions: []
  }
];

export const mockMatches: Match[] = [
  {
    id: 'match-1',
    maleId: 'g101',
    maleName: 'Ahmed Hassan',
    maleProfileApproved: true,
    malePhotoApproved: false,
    maleContactApproved: false,
    femaleId: 'l101',
    femaleName: 'Sara Mahmoud',
    femaleProfileApproved: true,
    femalePhotoApproved: false,
    femaleContactApproved: false,
    status: MatchStatus.PENDING_PHOTO_APPROVAL,
    notes: 'Both Ahmed and Sara loved each other\'s written profiles! Moving them to Phase 2: Photo Swap Approval.',
    responsibleAdminId: 'admin-sarah',
    responsibleAdminName: 'Sarah',
    createdAt: formatISO(subDays(now, 5)),
    updatedAt: formatISO(subDays(now, 3)),
    gentlemanCode: 'G101',
    ladyCode: 'L101'
  },
  {
    id: 'match-2',
    maleId: 'g102',
    maleName: 'Omar Farouk',
    maleProfileApproved: true,
    malePhotoApproved: true,
    maleContactApproved: true,
    femaleId: 'l102',
    femaleName: 'Salma Dawood',
    femaleProfileApproved: true,
    femalePhotoApproved: true,
    femaleContactApproved: true,
    status: MatchStatus.MATCH_ACTIVE,
    notes: 'Perfect Match! Mutual contact swap completed. Unlocked their direct phone lines. Admin following up in one week.',
    responsibleAdminId: 'admin-sarah',
    responsibleAdminName: 'Sarah',
    createdAt: formatISO(subDays(now, 12)),
    updatedAt: formatISO(subDays(now, 9)),
    gentlemanCode: 'G102',
    ladyCode: 'L102'
  },
  {
    id: 'match-3',
    maleId: 'g103',
    maleName: 'Karim Yassin',
    maleProfileApproved: false,
    malePhotoApproved: false,
    maleContactApproved: false,
    femaleId: 'l103',
    femaleName: 'Yasmine Sabry',
    femaleProfileApproved: false,
    femalePhotoApproved: false,
    femaleContactApproved: false,
    status: MatchStatus.PENDING_PROFILE_APPROVAL,
    notes: 'Match proposed by Youssef. Pending text profile review from both Karim and Yasmine.',
    responsibleAdminId: 'admin-youssef',
    responsibleAdminName: 'Youssef',
    createdAt: formatISO(subDays(now, 1)),
    updatedAt: formatISO(subDays(now, 1)),
    gentlemanCode: 'G103',
    ladyCode: 'L103'
  }
];
